# Generated by Django 5.2.7 on 2025-11-12 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0012_historicalproducteur_satellite_floraison_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date de réalisation')),
                ('impact_score', models.FloatField(help_text="Évaluation de l'efficacité de l'activité", verbose_name="Score d'impact (0-10)")),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût (Ar)')),
                ('resultats', models.TextField(blank=True, verbose_name='Résultats obtenus')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(max_length=100, verbose_name="Type d'activité")),
                ('description', models.TextField(verbose_name='Description de la recommandation')),
                ('score_pertinence', models.FloatField(help_text="Score calculé par l'IA", verbose_name='Score de pertinence (0-1)')),
                ('explication', models.TextField(blank=True, verbose_name='Explication de la recommandation')),
                ('date_generation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de génération')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('executed', 'Exécutée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('sources', models.JSONField(default=list, help_text='Liste des producteurs similaires ayant inspiré cette recommandation', verbose_name='Producteurs sources')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-date_generation', '-score_pertinence'],
                'indexes': [models.Index(fields=['producteur', 'statut'], name='recommandat_product_aae788_idx'), models.Index(fields=['date_generation'], name='recommandat_date_ge_e46973_idx')],
            },
        ),
    ]
