# Generated by Django 5.2.7 on 2026-02-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommandations', '0002_mahavelonaarchive'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mahavelonaarchive',
            new_name='recommandat_annee_r_1e9e7d_idx',
            old_name='recommandat_annee_r_94de3c_idx',
        ),
    ]
