# Generated by Django 5.2.7 on 2025-10-15 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='date_desactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='desactive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_desactives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producteur',
            name='raison_desactivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['actif', 'code'], name='producteurs_actif_730899_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['village'], name='producteurs_village_cfd3af_idx'),
        ),
    ]
