# Generated by Django 5.2.7 on 2025-10-15 10:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
        ('producteurs', '0002_producteur_date_desactivation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='producteur',
            name='producteurs_village_cfd3af_idx',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='adresse',
        ),
        migrations.AddField(
            model_name='producteur',
            name='a_assurance_sante',
            field=models.BooleanField(default=False, verbose_name='Possède une assurance santé'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='a_exploite_foret_apres_2019',
            field=models.BooleanField(default=False, verbose_name='A exploité la forêt après 2019'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='a_poubelles_triees',
            field=models.BooleanField(default=False, verbose_name='Dispose de 2 ou 3 types de poubelles'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='animaux_chasses',
            field=models.CharField(blank=True, help_text='Lambodia, Trandraka, Tomendry, Ankomba, autres', max_length=200, verbose_name="Types d'animaux chassés"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='animaux_eleves',
            field=models.CharField(blank=True, max_length=200, verbose_name="Types d'animaux élevés"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_3',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_4',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_5',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_6',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='autre_traitement_eau',
            field=models.CharField(blank=True, max_length=200, verbose_name="Autre méthode de traitement de l'eau"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='autres_enfants_foyer',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Autres enfants dans le foyer (hors propres enfants)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_6',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='cooperatives.cooperative'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='date_adhesion_groupement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'adhésion au groupement"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='dechets_chimiques_enterres',
            field=models.BooleanField(default=False, verbose_name="Déchets chimiques enterrés loin de l'eau"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='dechets_non_eparpilles_maison',
            field=models.BooleanField(default=False, verbose_name='Déchets non éparpillés dans la cour'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='dechets_non_eparpilles_parcelle',
            field=models.BooleanField(default=False, verbose_name='Déchets non éparpillés dans la parcelle'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='dotations_recues',
            field=models.TextField(blank=True, help_text='Nature et quantité des dotations', verbose_name='Dotations reçues'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='eau_potable',
            field=models.BooleanField(default=False, verbose_name='Eau potable'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fait_bouillir_eau',
            field=models.BooleanField(default=False, verbose_name="Fait bouillir l'eau"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fait_defrichage',
            field=models.BooleanField(default=False, verbose_name='Fait du défrichage ou travaille la pierre'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='femme_leader',
            field=models.BooleanField(default=False, help_text="Si femme, tient-elle une responsabilité au niveau du groupe d'épargne communautaire", verbose_name='Femme leader'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fokontany',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fokontany'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='formations_suivies',
            field=models.TextField(blank=True, verbose_name='Formations suivies'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fosse_eaux_usees_champ',
            field=models.BooleanField(default=False, verbose_name='Fosse pour eaux usées au champ'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fosse_eaux_usees_maison',
            field=models.BooleanField(default=False, verbose_name='Fosse pour eaux usées à la maison'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='lave_linge_riviere',
            field=models.BooleanField(default=False, verbose_name='Lave le linge/vaisselle dans la rivière'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='lieu_dechets_chimiques',
            field=models.TextField(blank=True, verbose_name='Lieu de dépôt des déchets chimiques si non enterrés'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='lieu_lavage',
            field=models.BooleanField(default=False, verbose_name="Dispose d'un lieu pour se laver"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='lieu_nettoyage_outils_chimiques',
            field=models.BooleanField(default=False, verbose_name='Lieu spécifique pour nettoyer les outils chimiques'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='membre_groupement_epargne',
            field=models.BooleanField(default=False, verbose_name="Membre d'une caisse communautaire (VSLA)"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_modifies', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_adultes_plus_18',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Personnes âgées de plus de 18 ans dans le foyer'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_autres_filles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Autres filles'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_autres_garcons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Autres garçons'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_enfants_filles',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Nombre d'enfants filles"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_enfants_garcons',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Nombre d'enfants garçons"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_enfants_non_scolarises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Enfants en âge d'être scolarisés mais non scolarisés"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_enfants_scolarises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Nombre d'enfants scolarisés"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_femmes_adultes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de femmes adultes'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='nb_hommes_adultes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'hommes adultes"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='ne_brule_pas_foret',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='ne_coupe_pas_foret',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='ne_cultive_pas_zone_protegee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_education',
            field=models.CharField(choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], default='primaire', max_length=20, verbose_name="Niveau d'éducation"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_1',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_2',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_3',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_4',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_5',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_6',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='participe_protection_environnement',
            field=models.BooleanField(default=True, verbose_name="Participe à la protection de l'environnement"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='participe_travaux_communautaires',
            field=models.BooleanField(default=True, verbose_name='Participe aux travaux communautaires'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='paysan_relais',
            field=models.BooleanField(default=False, verbose_name='Paysan relais'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='peche_eau_douce',
            field=models.BooleanField(default=False, verbose_name='Pêche en eau douce'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='peche_mer',
            field=models.BooleanField(default=False, verbose_name='Pêche en mer'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='personne_handicap_foyer',
            field=models.BooleanField(default=False, verbose_name='Personne en situation de handicap dans le foyer'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='pratique_chasse',
            field=models.BooleanField(default=False, verbose_name='Pratique la chasse'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='pratique_elevage',
            field=models.BooleanField(default=False, verbose_name="Pratique l'élevage"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='pratique_peche',
            field=models.BooleanField(default=False, verbose_name='Pratique la pêche'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='pratique_tavy',
            field=models.BooleanField(default=False, verbose_name='Pratique le brûlis agricole (Tavy)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='recyclage_dechets',
            field=models.BooleanField(default=False, verbose_name='Pratique le recyclage des déchets'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='recyclage_eau_pluie',
            field=models.BooleanField(default=False, verbose_name='Recyclage eau de pluie'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='respecte_dina',
            field=models.BooleanField(default=True, verbose_name='Participe au respect des conventions sociales (dina)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='respecte_loi_animaux_proteges',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='respecte_regles_peche',
            field=models.BooleanField(default=True, verbose_name='Respecte les règles de pêche'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='responsabilite_cooperative',
            field=models.CharField(choices=[('president_coop', 'Président Coopérative'), ('vice_president_coop', 'Vice Président Coopérative'), ('tresorier_coop', 'Trésorier Coopérative'), ('commissaire_coop', 'Commissaires aux comptes Coopérative'), ('secretaire_coop', 'Secrétaire Coopérative'), ('conseiller_coop', 'Conseillers Coopérative'), ('president_ca', 'Président CA'), ('vice_president_ca', 'Vice Président CA'), ('tresorier_ca', 'Trésorier CA'), ('commissaire_ca', 'Commissaires aux comptes CA'), ('conseiller_ca', 'Conseiller CA'), ('secretaire_ca', 'Secrétaire CA'), ('aucune', 'Aucune responsabilité')], default='aucune', max_length=30, verbose_name='Responsabilité dans la coopérative'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='source_eau',
            field=models.CharField(blank=True, choices=[('renirano', 'Rivière'), ('robinet', 'Robinet'), ('ranovovo', 'Puits')], max_length=20, verbose_name="Source d'approvisionnement en eau"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='statut_matrimonial',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('union_libre', 'Union libre'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, verbose_name='Civilité'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='stocke_chimiques_maison',
            field=models.BooleanField(default=False, verbose_name='Stocke des produits chimiques à la maison'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='type_centre_sante',
            field=models.CharField(blank=True, choices=[('csb1', 'CSB I'), ('csb2', 'CSB II'), ('hopitaly', 'Hôpital')], max_length=20, verbose_name='Type de centre de santé disponible'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='types_poubelles',
            field=models.CharField(blank=True, help_text='Types de poubelles séparés par virgules', max_length=200, verbose_name='Types de poubelles'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='utilise_chimiques_autres_cultures',
            field=models.BooleanField(default=False, verbose_name='Utilise des produits chimiques sur autres cultures'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='utilise_sureau',
            field=models.BooleanField(default=False, verbose_name="Utilise Sur'eau"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='verifie',
            field=models.BooleanField(default=False, verbose_name='Profil vérifié'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_verifies', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='wc_champ',
            field=models.BooleanField(default=False, verbose_name='WC au champ'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='wc_maison',
            field=models.BooleanField(default=False, verbose_name='WC à la maison'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code Producteur'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='commune',
            field=models.CharField(max_length=100, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='date_adhesion',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'adhésion"),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='date_naissance',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='producteurs/photos/', verbose_name='Photo du producteur'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='N° Téléphone'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='village',
            field=models.CharField(max_length=100, verbose_name='Village'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['village', 'commune'], name='producteurs_village_54087d_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['cooperative'], name='producteurs_coopera_227304_idx'),
        ),
    ]
