# Generated by Django 5.2.7 on 2025-10-15 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0003_remove_producteur_producteurs_village_cfd3af_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producteur',
            name='cin',
            field=models.CharField(blank=True, help_text='Format: XXX XXX XXX XXX (12 chiffres)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Format CIN invalide. Utilisez: XXX XXX XXX XXX (12 chiffres)', regex='^\\d{3}\\s?\\d{3}\\s?\\d{3}\\s?\\d{3}$')], verbose_name='CIN'),
        ),
    ]
