# Generated by Django 5.2.7 on 2025-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0004_producteur_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
    ]
