# Generated by Django 5.2.7 on 2025-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0005_alter_producteur_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='niveau_education',
            field=models.CharField(choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], default='', max_length=20, verbose_name="Niveau d'éducation"),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='statut_matrimonial',
            field=models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('union_libre', 'Union libre'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, null=True, verbose_name='Civilité'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='N° Téléphone'),
        ),
    ]
