# Generated by Django 5.2.7 on 2025-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0007_historicalproducteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducteur',
            name='cin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='historicalproducteur',
            name='fokontany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fokontany'),
        ),
        migrations.AlterField(
            model_name='historicalproducteur',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='cin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='fokontany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fokontany'),
        ),
        migrations.AlterField(
            model_name='producteur',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Village'),
        ),
    ]
