# Generated by Django 5.2.7 on 2025-11-01 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0008_alter_historicalproducteur_cin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducteur',
            name='enfants_doit_scolarises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Enfants qui doivent aller à l'école"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='enfants_doit_scolarises',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name="Enfants qui doivent aller à l'école"),
        ),
    ]
