# Generated by Django 5.2.7 on 2025-11-05 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0009_historicalproducteur_enfants_doit_scolarises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducteur',
            name='enfants_doit_scolarises',
        ),
        migrations.RemoveField(
            model_name='producteur',
            name='enfants_doit_scolarises',
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='annee_naissance_enfant_10',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='annee_naissance_enfant_7',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='annee_naissance_enfant_8',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='annee_naissance_enfant_9',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='continue_ecole_enfant_10',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='continue_ecole_enfant_7',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='continue_ecole_enfant_8',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='continue_ecole_enfant_9',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='niveau_etude_enfant_10',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='niveau_etude_enfant_7',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='niveau_etude_enfant_8',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='niveau_etude_enfant_9',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_10',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_7',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_8',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_naissance_enfant_9',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_10',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_7',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_8',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='continue_ecole_enfant_9',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_10',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_7',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_8',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
        migrations.AddField(
            model_name='producteur',
            name='niveau_etude_enfant_9',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], max_length=20),
        ),
    ]
