# Generated by Django 5.2.7 on 2025-11-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0002_add_activites_fields'),
        ('producteurs', '0010_remove_historicalproducteur_enfants_doit_scolarises_and_more'),
    ]

    operations = [
    ]
