# Generated by Django 5.2.7 on 2025-11-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0011_merge_20251109_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducteur',
            name='satellite_floraison',
            field=models.BooleanField(default=False, verbose_name='Satellite floraison'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='satellite_floraison',
            field=models.BooleanField(default=False, verbose_name='Satellite floraison'),
        ),
    ]
