# Generated by Django 5.2.7 on 2025-12-23 07:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0012_historicalproducteur_satellite_floraison_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducteur',
            name='annee_stat_scolarisation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de référence du taux de scolarisation'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='date_adhesion_cooperative',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'adhésion à la coopérative"),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='mahavelona_annee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'adhésion Mahavelona"),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='mahavelona_criteres_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Version des critères Mahavelona'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='taux_scolarisation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de scolarisation (%)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='annee_stat_scolarisation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de référence du taux de scolarisation'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='date_adhesion_cooperative',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'adhésion à la coopérative"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='mahavelona_annee',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Année d'adhésion Mahavelona"),
        ),
        migrations.AddField(
            model_name='producteur',
            name='mahavelona_criteres_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Version des critères Mahavelona'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='taux_scolarisation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de scolarisation (%)'),
        ),
        migrations.CreateModel(
            name='Dotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dotation', models.CharField(choices=[('kit_scolaire', 'Kit scolaire'), ('poisson', 'Poisson'), ('volaille', 'Volaille'), ('autre', 'Autre')], max_length=30, verbose_name='Type de dotation')),
                ('annee', models.PositiveIntegerField(verbose_name='Année de dotation')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité / nombre de kits')),
                ('details', models.CharField(blank=True, max_length=255, verbose_name='Détails complémentaires')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dotations_creees', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dotations', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Dotation',
                'verbose_name_plural': 'Dotations',
                'ordering': ['-annee', '-date_enregistrement'],
                'unique_together': {('producteur', 'type_dotation', 'annee', 'details')},
            },
        ),
    ]
