# Generated by Django - manually created

from django.db import migrations, models


def copy_date_adhesion_to_cooperative(apps, schema_editor):
    """
    Copie date_adhesion vers date_adhesion_cooperative si ce dernier est vide
    """
    Producteur = apps.get_model('producteurs', 'Producteur')
    
    # Pour tous les producteurs où date_adhesion_cooperative est vide
    producteurs_to_update = Producteur.objects.filter(
        date_adhesion_cooperative__isnull=True
    ).exclude(date_adhesion__isnull=True)
    
    for producteur in producteurs_to_update:
        producteur.date_adhesion_cooperative = producteur.date_adhesion
        producteur.save(update_fields=['date_adhesion_cooperative'])
    
    print(f"[0014] {producteurs_to_update.count()} producteurs mis a jour")


def reverse_copy(apps, schema_editor):
    """
    Migration inverse - ne fait rien car on ne peut pas recréer date_adhesion
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0013_historicalproducteur_annee_stat_scolarisation_and_more'),
    ]

    operations = [
        # D'abord, s'assurer que date_adhesion_cooperative n'est pas null pour les données existantes
        migrations.RunPython(copy_date_adhesion_to_cooperative, reverse_copy),
        
        # Supprimer date_adhesion du modèle
        migrations.RemoveField(
            model_name='producteur',
            name='date_adhesion',
        ),
        
        # Supprimer date_adhesion de l'historique aussi
        migrations.RemoveField(
            model_name='historicalproducteur',
            name='date_adhesion',
        ),
    ]
