# Generated by Django 5.2.7 on 2025-12-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0014_remove_date_adhesion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producteur',
            options={'ordering': ['-date_adhesion_cooperative', '-date_modification'], 'verbose_name': 'Producteur', 'verbose_name_plural': 'Producteurs'},
        ),
    ]
