# Generated by Django 5.2.7 on 2026-01-04 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0004_cooperative_annee_creation'),
        ('producteurs', '0015_alter_producteur_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['cooperative', 'date_adhesion_cooperative'], name='producteurs_coopera_728950_idx'),
        ),
    ]
