# Generated by Django 5.2.7 on 2026-01-20 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0016_producteur_producteurs_coopera_728950_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_agr', models.CharField(choices=[('pisciculture', 'Pisciculture'), ('aviculture', 'Aviculture'), ('autre', 'Autre')], max_length=100, verbose_name="Type d'AGR")),
                ('ordre', models.IntegerField(help_text='1 pour AGR1, 2 pour AGR2', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('intrants_recus', models.BooleanField(default=False, verbose_name='Intrants reçus')),
                ('quantite_intrants', models.IntegerField(blank=True, help_text="Nombre d'intrants reçus (alevins, poussins, etc.)", null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Quantité d'intrants reçus")),
                ('utilisation', models.CharField(blank=True, choices=[('consommation', 'À consommer'), ('vente', 'À vendre'), ('les_deux', 'Les deux')], max_length=20, verbose_name="Type d'utilisation")),
                ('quantite_consommee_annuelle', models.DecimalField(blank=True, decimal_places=2, help_text='Quantité consommée par an (kg ou nombre)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité consommée par an')),
                ('quantite_vendue_annuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité vendue par an')),
                ('unite_mesure', models.CharField(default='kg', help_text='kg, nombre, etc.', max_length=20, verbose_name='Unité de mesure')),
                ('prix_vente_unitaire', models.DecimalField(blank=True, decimal_places=2, help_text='Prix de vente unitaire en Ariary', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente unitaire')),
                ('revenu_annuel_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Calculé: quantite_vendue × prix_vente', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenu annuel estimé')),
                ('nombre_bassins', models.IntegerField(blank=True, help_text='Pour pisciculture', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de bassins')),
                ('nombre_volailles', models.IntegerField(blank=True, help_text='Pour aviculture', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de volailles')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agr_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agr_activities', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'AGR',
                'verbose_name_plural': 'AGR',
                'ordering': ['producteur', 'ordre'],
                'indexes': [models.Index(fields=['producteur'], name='producteurs_product_68436d_idx'), models.Index(fields=['type_agr'], name='producteurs_type_ag_3428d2_idx'), models.Index(fields=['active'], name='producteurs_active_c0abe3_idx')],
                'unique_together': {('producteur', 'ordre')},
            },
        ),
    ]
