# Generated by Django 5.2.7 on 2026-01-21 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0017_agr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agr',
            name='ordre',
            field=models.IntegerField(help_text="Ordre de l'AGR (1, 2, 3, ...)", validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
