# Generated by Django 5.2.7 on 2026-08-05 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_region'),
        ('producteurs', '0018_alter_agr_ordre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dotation',
            index=models.Index(fields=['producteur'], name='producteurs_product_462e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='dotation',
            index=models.Index(fields=['type_dotation'], name='producteurs_type_do_862782_idx'),
        ),
        migrations.AddIndex(
            model_name='dotation',
            index=models.Index(fields=['annee'], name='producteurs_annee_2c817c_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['sexe'], name='producteurs_sexe_67328d_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['femme_leader'], name='producteurs_femme_l_8180b6_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['paysan_relais'], name='producteurs_paysan__f7c99d_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['verifie'], name='producteurs_verifie_04ebd2_idx'),
        ),
        migrations.AddIndex(
            model_name='producteur',
            index=models.Index(fields=['mahavelona'], name='producteurs_mahavel_fbb45a_idx'),
        ),
    ]
