# Generated by Django 5.2.7 on 2026-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0001_initial'),
        ('producteurs', '0019_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducteur',
            name='commune_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.commune', verbose_name='Commune (référentiel)'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='fokontany_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.fokontany', verbose_name='Fokontany (référentiel)'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.region', verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='structure_intermediaire',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.structureintermediaire', verbose_name='Structure intermédiaire'),
        ),
        migrations.AddField(
            model_name='historicalproducteur',
            name='village_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geographie.village', verbose_name='Village (référentiel)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='commune_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.commune', verbose_name='Commune (référentiel)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='fokontany_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.fokontany', verbose_name='Fokontany (référentiel)'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.region', verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='structure_intermediaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.structureintermediaire', verbose_name='Structure intermédiaire'),
        ),
        migrations.AddField(
            model_name='producteur',
            name='village_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs', to='geographie.village', verbose_name='Village (référentiel)'),
        ),
    ]
