# Generated by Django 5.2.7 on 2025-10-15 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooperative',
            options={'ordering': ['-date_enregistrement'], 'verbose_name': 'Coopérative', 'verbose_name_plural': 'Coopératives'},
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='actif',
        ),
        migrations.RemoveField(
            model_name='cooperative',
            name='adresse',
        ),
        migrations.AddField(
            model_name='cooperative',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='certifiee',
            field=models.BooleanField(default=False, verbose_name='Certifiée'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='date_agrement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'agrément"),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='date_enregistrement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='fokontany',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fokontany'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cooperatives/logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='nombre_femmes',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de femmes'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='nombre_hommes',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre d'hommes"),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='nombre_membres',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de membres'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='numero_agrement',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='objectifs',
            field=models.TextField(blank=True, verbose_name='Objectifs'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='president_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du président'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='president_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone président'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Région'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='secretaire_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du secrétaire'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='secretaire_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone secrétaire'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='tresorier_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom du trésorier'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='tresorier_telephone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Téléphone trésorier'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='type_certification',
            field=models.CharField(blank=True, choices=[('bio', 'Agriculture Biologique'), ('commerce_equitable', 'Commerce Équitable'), ('rainforest', 'Rainforest Alliance'), ('autre', 'Autre')], max_length=50, verbose_name='Type de certification'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='code',
            field=models.CharField(help_text='Code unique de la coopérative (ex: COOP001)', max_length=20, unique=True, verbose_name='Code coopérative'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='commune',
            field=models.CharField(max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date de création officielle de la coopérative', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom de la coopérative'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='sigle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format: +261XXXXXXXXX', regex='^\\+?261\\d{9,10}$')], verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='cooperative',
            name='village',
            field=models.CharField(max_length=100, null=True, verbose_name='Village'),
        ),
        migrations.AddIndex(
            model_name='cooperative',
            index=models.Index(fields=['code'], name='cooperative_code_b5fa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperative',
            index=models.Index(fields=['commune'], name='cooperative_commune_a32a77_idx'),
        ),
        migrations.AddIndex(
            model_name='cooperative',
            index=models.Index(fields=['active'], name='cooperative_active_769942_idx'),
        ),
    ]
