# Generated by Django 5.2.7 on 2025-10-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0002_alter_cooperative_options_remove_cooperative_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='code',
            field=models.CharField(help_text='Code unique de la coopérative (ex: COOP001)', max_length=50, unique=True, verbose_name='Code coopérative'),
        ),
    ]
