# Generated by Django 5.2.7 on 2025-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_alter_cooperative_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='annee_creation',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de création'),
        ),
    ]
