# Generated by Django 5.2.7 on 2026-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_region'),
        ('geographie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.agence', verbose_name='Agence RAMEX'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='commune_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.commune', verbose_name='Commune (référentiel)'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='district_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.district', verbose_name='District (référentiel)'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='fokontany_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.fokontany', verbose_name='Fokontany (référentiel)'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='region_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.region', verbose_name='Région (référentiel)'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='village_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperatives', to='geographie.village', verbose_name='Village (référentiel)'),
        ),
    ]
