# Generated by Django 5.2.7 on 2026-08-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0006_cooperative_agence_cooperative_commune_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperative',
            name='objectifs_dd',
            field=models.JSONField(blank=True, default=list, help_text='Liste des objectifs clients DD (résilience, autonomisation femmes, droits humains, biodiversité...)', verbose_name='Objectifs Développement Durable'),
        ),
    ]
