# Generated by Django 5.2.7 on 2026-09-01 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_cooperative_objectifs_dd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperative',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Date de création officielle de la coopérative', verbose_name='Date de création'),
        ),
    ]
