# Generated by Django 5.2.7 on 2025-10-15 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0003_remove_producteur_producteurs_village_cfd3af_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.PositiveIntegerField(help_text='P1, P2, P3...', verbose_name='Numéro de parcelle')),
                ('code_parcelle', models.CharField(help_text='Code unique de la parcelle (ex: PROD001-P1)', max_length=50, unique=True, verbose_name='Code parcelle')),
                ('localisation', models.CharField(help_text='Fokontany/Faritra', max_length=200, verbose_name='Localisation')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='GPS Latitude')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='GPS Longitude')),
                ('dimension_ha', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dimension (Ha)')),
                ('nombre_pieds', models.PositiveIntegerField(default=0, verbose_name='Nombre de pieds de vanille')),
                ('annee_plantation', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de plantation')),
                ('type_vanille', models.CharField(choices=[('planifolia', 'Planifolia'), ('tahitensis', 'Tahitensis'), ('pompona', 'Pompona')], default='planifolia', max_length=50, verbose_name='Type de vanille cultivé')),
                ('estimation_production_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimation de production (kg)')),
                ('cultures_autour', models.TextField(blank=True, verbose_name='Types de cultures autour de la parcelle')),
                ('profil_parcelle', models.CharField(blank=True, choices=[('en_pente', 'En pente'), ('parc_naturel', "À proximité d'un Parc Naturel"), ('reserve_naturelle', "À proximité d'une Réserve Naturelle"), ('zone_tampon', 'Dans une zone tampon'), ('source_eau', "À proximité d'une source d'eau")], max_length=50, verbose_name='Profil de la parcelle')),
                ('distance_habitation', models.CharField(blank=True, choices=[('moins_1h', 'Moins de 1h'), ('1h_2h', '1h - 2h'), ('2h_3h', '2h - 3h'), ('plus_4h', 'Plus de 4h')], max_length=20, verbose_name="Distance de l'habitation")),
                ('type_propriete', models.CharField(choices=[('terrain_propre', 'Terrain propre'), ('terrain_loue', 'Terrain loué'), ('les_deux', 'Les deux')], default='terrain_propre', max_length=50, verbose_name='Type de propriété')),
                ('certifiee', models.BooleanField(default=False, verbose_name='Parcelle certifiée')),
                ('type_certification', models.CharField(blank=True, choices=[('g4g', 'G4G'), ('ra', 'Rainforest Alliance'), ('uebt', 'UEBT'), ('ffl', 'FFL'), ('ft', 'Fair Trade'), ('bio', 'BIO'), ('pact', 'PACT')], max_length=20, verbose_name='Type de certification')),
                ('photo_parcelle', models.ImageField(blank=True, null=True, upload_to='parcelles/photos/', verbose_name='Photo de la parcelle')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelles_modifiees', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['producteur', 'numero_parcelle'],
                'indexes': [models.Index(fields=['code_parcelle'], name='parcelles_p_code_pa_b97eb1_idx'), models.Index(fields=['producteur'], name='parcelles_p_product_244136_idx')],
                'unique_together': {('producteur', 'numero_parcelle')},
            },
        ),
    ]
