# Generated by Django 5.2.7 on 2025-10-19 05:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Coordonnées GPS de la parcelle', null=True, srid=4326, verbose_name='Position GPS (Point)'),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='polygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='Contours de la parcelle', null=True, srid=4326, verbose_name='Délimitation (Polygone)'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='GPS Latitude (Ancien)'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='GPS Longitude (Ancien)'),
        ),
    ]
