# Generated by Django 5.2.7 on 2025-10-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_parcelle_point_parcelle_polygon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='localisation',
            field=models.CharField(blank=True, default='Non renseigné', help_text='Fokontany/Faritra', max_length=200, verbose_name='Localisation'),
        ),
    ]
