# Generated by Django 5.2.7 on 2025-10-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0003_alter_parcelle_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='culture_principale',
            field=models.CharField(choices=[('vanille', 'Vanille'), ('cafe', 'Café'), ('girofle', 'Girofle'), ('autre', 'Autre')], default='vanille', max_length=20, verbose_name='Culture principale'),
        ),
    ]
