# Generated by Django 5.2.7 on 2025-10-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0004_parcelle_culture_principale'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='cultures_pratiquees',
            field=models.JSONField(blank=True, default=list, help_text="Liste des cultures pratiquées sur cette parcelle (ex: ['vanille', 'cafe', 'girofle'])", verbose_name='Cultures pratiquées'),
        ),
    ]
