# Generated by Django 5.2.7 on 2025-12-23 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0006_parcelle_productions_par_culture'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='annee_creation',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de création / acquisition'),
        ),
    ]
