# Generated by Django 5.2.7 on 2026-08-05 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_parcelle_annee_creation'),
        ('producteurs', '0018_alter_agr_ordre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['certifiee'], name='parcelles_p_certifi_7772c3_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['type_vanille'], name='parcelles_p_type_va_57c5c2_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['active'], name='parcelles_p_active_c9ff86_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['culture_principale'], name='parcelles_p_culture_22d6eb_idx'),
        ),
    ]
