# Generated by Django 5.2.7 on 2026-01-21 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0007_parcelle_annee_creation'),
        ('producteurs', '0018_alter_agr_ordre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AGRHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('type_agr', models.CharField(choices=[('pisciculture', 'Pisciculture'), ('aviculture', 'Aviculture'), ('autre', 'Autre')], max_length=100, verbose_name="Type d'AGR")),
                ('ordre', models.IntegerField(help_text='AGR1, AGR2, etc.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre')),
                ('quantite_produite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité produite')),
                ('quantite_vendue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité vendue')),
                ('quantite_consommee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité consommée')),
                ('prix_vente_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente unitaire (Ar)')),
                ('revenu_annuel', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenu annuel (Ar)')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agr_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agr_history', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Historique AGR',
                'verbose_name_plural': 'Historiques AGR',
                'ordering': ['-annee', 'producteur', 'ordre'],
                'indexes': [models.Index(fields=['annee'], name='history_agr_annee_16c7d8_idx'), models.Index(fields=['producteur', 'annee'], name='history_agr_product_0d52c4_idx'), models.Index(fields=['type_agr', 'annee'], name='history_agr_type_ag_76ba53_idx')],
                'unique_together': {('producteur', 'annee', 'type_agr', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='AnnualSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('nb_producteurs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de producteurs')),
                ('nb_parcelles', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nombre de parcelles')),
                ('production_totale_kg', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Production totale (kg)')),
                ('revenu_total_agr', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenu total AGR (Ar)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('verrouille', models.BooleanField(default=False, help_text='Un snapshot verrouillé ne peut plus être modifié', verbose_name='Verrouillé')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Snapshot annuel',
                'verbose_name_plural': 'Snapshots annuels',
                'ordering': ['-annee'],
                'indexes': [models.Index(fields=['annee'], name='history_ann_annee_543949_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('culture', models.CharField(help_text='vanille, cafe, girofle, etc.', max_length=50, verbose_name='Type de culture')),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité produite (kg)')),
                ('prix_vente_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de vente par kg (Ar)')),
                ('revenu_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Revenu total (Ar)')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_history', to='parcelles.parcelle', verbose_name='Parcelle')),
            ],
            options={
                'verbose_name': 'Historique de production',
                'verbose_name_plural': 'Historiques de production',
                'ordering': ['-annee', 'parcelle'],
                'indexes': [models.Index(fields=['annee'], name='history_pro_annee_f31cb2_idx'), models.Index(fields=['parcelle', 'annee'], name='history_pro_parcell_879ce9_idx'), models.Index(fields=['culture', 'annee'], name='history_pro_culture_b4a1a8_idx')],
                'unique_together': {('parcelle', 'annee', 'culture')},
            },
        ),
        migrations.CreateModel(
            name='SocialIndicatorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('type_indicateur', models.CharField(choices=[('scolarisation', 'Taux de scolarisation'), ('eau_potable', 'Accès eau potable'), ('sante', 'Accès aux soins'), ('habitat', 'Type de logement'), ('energie', "Accès à l'énergie")], max_length=50, verbose_name="Type d'indicateur")),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur numérique')),
                ('valeur_texte', models.CharField(blank=True, max_length=200, verbose_name='Valeur texte')),
                ('valeur_booleen', models.BooleanField(blank=True, null=True, verbose_name='Valeur booléenne')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicateurs_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_indicator_history', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': "Historique d'indicateur social",
                'verbose_name_plural': "Historiques d'indicateurs sociaux",
                'ordering': ['-annee', 'producteur'],
                'indexes': [models.Index(fields=['annee'], name='history_soc_annee_b28f1d_idx'), models.Index(fields=['producteur', 'annee'], name='history_soc_product_4df29a_idx'), models.Index(fields=['type_indicateur', 'annee'], name='history_soc_type_in_ca3f88_idx')],
                'unique_together': {('producteur', 'annee', 'type_indicateur')},
            },
        ),
    ]
