# Generated by Django 5.2.7 on 2026-02-07 23:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('producteurs', '0018_alter_agr_ordre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducteurSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('cin', models.CharField(blank=True, max_length=15, verbose_name='CIN')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('fokontany', models.CharField(blank=True, max_length=100, verbose_name='Fokontany')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('sexe', models.CharField(max_length=1, verbose_name='Sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('statut_matrimonial', models.CharField(blank=True, max_length=20, verbose_name='Statut matrimonial')),
                ('niveau_education', models.CharField(blank=True, max_length=20, verbose_name="Niveau d'éducation")),
                ('femme_leader', models.BooleanField(default=False, verbose_name='Femme leader')),
                ('cooperative_nom', models.CharField(blank=True, max_length=200, verbose_name='Nom de la coopérative')),
                ('responsabilite_cooperative', models.CharField(blank=True, max_length=30, verbose_name='Responsabilité')),
                ('date_adhesion_cooperative', models.DateField(blank=True, null=True, verbose_name='Date adhésion coop')),
                ('date_adhesion_groupement', models.DateField(blank=True, null=True, verbose_name='Date adhésion groupement')),
                ('membre_groupement_epargne', models.BooleanField(default=False, verbose_name='Membre VSLA')),
                ('paysan_relais', models.BooleanField(default=False, verbose_name='Paysan relais')),
                ('satellite_floraison', models.BooleanField(default=False, verbose_name='Satellite floraison')),
                ('nb_adultes_plus_18', models.IntegerField(default=0, verbose_name='Adultes 18+')),
                ('nb_hommes_adultes', models.IntegerField(default=0, verbose_name='Hommes adultes')),
                ('nb_femmes_adultes', models.IntegerField(default=0, verbose_name='Femmes adultes')),
                ('nb_enfants_garcons', models.IntegerField(default=0, verbose_name='Garçons')),
                ('nb_enfants_filles', models.IntegerField(default=0, verbose_name='Filles')),
                ('nb_enfants_scolarises', models.IntegerField(default=0, verbose_name='Enfants scolarisés')),
                ('nb_enfants_non_scolarises', models.IntegerField(default=0, verbose_name='Enfants non scolarisés')),
                ('taux_scolarisation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux scolarisation')),
                ('source_eau', models.CharField(blank=True, max_length=20, verbose_name="Source d'eau")),
                ('type_centre_sante', models.CharField(blank=True, max_length=20, verbose_name='Type CSB')),
                ('a_assurance_sante', models.BooleanField(default=False, verbose_name='Assurance santé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteur_snapshots_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Snapshot Producteur',
                'verbose_name_plural': 'Snapshots Producteurs',
                'ordering': ['-annee', 'producteur'],
                'indexes': [models.Index(fields=['annee'], name='history_pro_annee_a490d3_idx'), models.Index(fields=['producteur', 'annee'], name='history_pro_product_c8a621_idx'), models.Index(fields=['commune', 'annee'], name='history_pro_commune_080dd4_idx'), models.Index(fields=['cooperative_nom', 'annee'], name='history_pro_coopera_3cfcae_idx')],
                'unique_together': {('producteur', 'annee')},
            },
        ),
    ]
