# Generated by Django 5.2.7 on 2026-01-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VillageReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('commune', models.CharField(blank=True, max_length=150, null=True)),
                ('fokontany', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='dashboard_v_name_198371_idx'), models.Index(fields=['commune'], name='dashboard_v_commune_481943_idx'), models.Index(fields=['fokontany'], name='dashboard_v_fokonta_59959c_idx')],
                'unique_together': {('name', 'commune', 'fokontany')},
            },
        ),
    ]
