# Generated by Django 5.2.7 on 2026-01-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_region_to_village_reference'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='villagereference',
            new_name='dashboard_v_region_eb3381_idx',
            old_name='dashboard_v_region_idx',
        ),
    ]
