# Generated by Django 5.2.7 on 2026-08-27 06:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracabilite', '0009_magasin_campagne_type_bonlivraison_entreemagasin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code de la phase')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la phase')),
                ('pilier', models.CharField(choices=[('tracabilite', 'Traçabilité'), ('certification', 'Certification'), ('developpement_durable', 'Développement Durable')], max_length=30, verbose_name='Pilier')),
                ('type_phase', models.CharField(choices=[('floraison', 'Floraison'), ('recolte_verte', 'Récolte vanille verte'), ('recolte_preparee', 'Récolte vanille préparée'), ('georeferencement', 'Géoréférencement GPS'), ('formation', 'Formation'), ('controle_interne', 'Contrôle interne'), ('audit_interne', 'Audit interne'), ('expedition', 'Expédition'), ('reboisement', 'Reboisement'), ('convention', 'Convention / partenariat'), ('pepiniere', 'Pépinière')], max_length=30, verbose_name='Type de phase')),
                ('mois_debut', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois début (1-12)')),
                ('mois_fin', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois fin (1-12)')),
                ('cycle_croise', models.BooleanField(default=False, help_text='True si la fenêtre dépasse décembre (ex: Nov-Déc formation 2e cycle)', verbose_name="Cycle chevauchant l'année")),
                ('toute_annee', models.BooleanField(default=False, verbose_name="Fenêtre étalée toute l'année")),
                ('couleur', models.CharField(default='#2563eb', max_length=20, verbose_name='Couleur (hex)')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phase agricole',
                'verbose_name_plural': 'Phases agricoles',
                'ordering': ['pilier', 'ordre', 'mois_debut', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='IndicateurCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name="Libellé de l'indicateur")),
                ('type', models.CharField(choices=[('quantite', 'Quantité (kg)'), ('montant', 'Montant (Ar)'), ('valeur', 'Valeur (USD)'), ('nombre', 'Nombre'), ('taux', 'Taux (%)'), ('texte', 'Texte')], default='quantite', max_length=20)),
                ('objectif', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Objectif')),
                ('realise', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Réalisé')),
                ('pilier', models.CharField(choices=[('tracabilite', 'Traçabilité'), ('certification', 'Certification'), ('developpement_durable', 'Développement Durable')], default='tracabilite', max_length=30, verbose_name='Pilier')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='tracabilite.campagne', verbose_name='Campagne')),
            ],
            options={
                'verbose_name': 'Indicateur de campagne',
                'verbose_name_plural': 'Indicateurs de campagne',
                'ordering': ['campagne', 'pilier', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhaseCampagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Début réel')),
                ('date_fin', models.DateField(verbose_name='Fin réelle')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('objectif', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Objectif (quantité/valeur)')),
                ('realise', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Réalisé')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases_planifiees', to='tracabilite.campagne', verbose_name='Campagne')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campagnes_phase', to='cycle_annuel.phaseagricole', verbose_name='Phase agricole')),
            ],
            options={
                'verbose_name': 'Phase planifiée (campagne)',
                'verbose_name_plural': 'Phases planifiées (campagne)',
                'ordering': ['date_debut', 'phase__ordre'],
                'unique_together': {('campagne', 'phase')},
            },
        ),
    ]
