# Generated by Django 5.2.7 on 2025-10-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteurs', '0008_alter_historicalproducteur_cin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la certification')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('niveau', models.CharField(choices=[('bio', 'BIO'), ('fair_trade', 'Fair Trade'), ('rainforest', 'Rainforest Alliance'), ('uebt', 'UEBT'), ('g4g', 'Good4Good'), ('ffl', 'FFL'), ('pact', 'PACT'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Niveau/Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('organisme_certificateur', models.CharField(blank=True, max_length=200, verbose_name='Organisme certificateur')),
                ('duree_validite_ans', models.IntegerField(default=1, verbose_name='Durée de validité (ans)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de Certification',
                'verbose_name_plural': 'Types de Certifications',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la formation')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_jours', models.IntegerField(default=1, verbose_name='Durée (jours)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de Formation',
                'verbose_name_plural': 'Types de Formations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificat', models.CharField(blank=True, max_length=100, verbose_name='Numéro de certificat')),
                ('date_obtention', models.DateField(verbose_name="Date d'obtention")),
                ('date_expiration', models.DateField(verbose_name="Date d'expiration")),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expire', 'Expiré'), ('en_cours', "En cours d'obtention"), ('suspendu', 'Suspendu')], default='valide', max_length=20, verbose_name='Statut')),
                ('fichier_certificat', models.FileField(blank=True, null=True, upload_to='certifications/', verbose_name='Fichier du certificat')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_modifiees', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='producteurs.producteur', verbose_name='Producteur')),
                ('type_certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certifications', to='formations.typecertification', verbose_name='Type de certification')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-date_obtention'],
                'indexes': [models.Index(fields=['producteur', 'statut'], name='formations__product_a35eb8_idx'), models.Index(fields=['date_expiration'], name='formations__date_ex_7d6f87_idx')],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_formation', models.DateField(verbose_name='Date de la formation')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('organisme', models.CharField(blank=True, max_length=200, verbose_name='Organisme formateur')),
                ('certificat_obtenu', models.BooleanField(default=False, verbose_name='Certificat obtenu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='producteurs.producteur', verbose_name='Producteur')),
                ('type_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='formations.typeformation', verbose_name='Type de formation')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_formation'],
                'indexes': [models.Index(fields=['producteur', 'date_formation'], name='formations__product_9dcdd5_idx')],
            },
        ),
    ]
