# Generated by Django 5.2.7 on 2026-01-04 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        ('producteurs', '0016_producteur_producteurs_coopera_728950_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_audit', models.DateField(verbose_name="Date d'audit")),
                ('organisme', models.CharField(blank=True, max_length=200, verbose_name="Organisme d'audit")),
                ('resultat', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme'), ('observations', 'Avec observations')], max_length=20, verbose_name='Résultat')),
                ('rapport_fichier', models.FileField(blank=True, null=True, upload_to='audits/', verbose_name="Rapport d'audit")),
                ('resume', models.TextField(blank=True, verbose_name='Résumé/constats')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit de Certification',
                'verbose_name_plural': 'Audits de Certification',
                'ordering': ['-date_audit'],
            },
        ),
        migrations.CreateModel(
            name='NonConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mineure', 'Mineure'), ('majeure', 'Majeure'), ('critique', 'Critique')], default='mineure', max_length=20, verbose_name='Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('action_corrective', models.TextField(blank=True, verbose_name='Action corrective')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('date_resolution', models.DateField(blank=True, null=True, verbose_name='Date de résolution')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('resolue', 'Résolue')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('fichier_preuve', models.FileField(blank=True, null=True, upload_to='audits/preuves/', verbose_name='Preuve')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Non-conformité',
                'verbose_name_plural': 'Non-conformités',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['date_obtention'], name='formations__date_ob_2cc4fe_idx'),
        ),
        migrations.AddField(
            model_name='auditcertification',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditcertification',
            name='type_certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='formations.typecertification', verbose_name='Type de certification'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformites', to='formations.auditcertification', verbose_name='Audit'),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformites_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nonconformite',
            name='producteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonconformites', to='producteurs.producteur', verbose_name='Producteur concerné'),
        ),
        migrations.AddIndex(
            model_name='auditcertification',
            index=models.Index(fields=['type_certification', 'date_audit'], name='formations__type_ce_266ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformite',
            index=models.Index(fields=['statut'], name='formations__statut_8ff76a_idx'),
        ),
        migrations.AddIndex(
            model_name='nonconformite',
            index=models.Index(fields=['date_limite'], name='formations__date_li_b0e6d1_idx'),
        ),
    ]
