# Generated by Django 5.2.7 on 2026-08-24 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0007_cooperative_objectifs_dd'),
        ('formations', '0002_auditcertification_nonconformite_and_more'),
        ('producteurs', '0020_historicalproducteur_commune_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('sensibilisation', 'Sensibilisation'), ('formation', 'Formation'), ('audit_interne', 'Audit interne'), ('audit_externe', 'Audit externe')], max_length=30, verbose_name="Type d'activité")),
                ('date', models.DateField(verbose_name="Date de l'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description / thèmes abordés')),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat obtenu')),
                ('nombre_participants', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Activité de certification',
                'verbose_name_plural': 'Activités de certification',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='certification',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='cooperatives.cooperative', verbose_name='Coopérative'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='producteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='producteurs.producteur', verbose_name='Producteur'),
        ),
        migrations.AddIndex(
            model_name='certification',
            index=models.Index(fields=['cooperative', 'statut'], name='formations__coopera_1d5d88_idx'),
        ),
        migrations.AddField(
            model_name='activitecertification',
            name='cooperative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_certification', to='cooperatives.cooperative', verbose_name='Coopérative concernée'),
        ),
        migrations.AddField(
            model_name='activitecertification',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_certification_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='activitecertification',
            name='producteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_certification', to='producteurs.producteur', verbose_name='Producteur concerné'),
        ),
        migrations.AddField(
            model_name='activitecertification',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_certification_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Agent RAMEX responsable'),
        ),
        migrations.AddField(
            model_name='activitecertification',
            name='type_certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='formations.typecertification', verbose_name='Type de certification lié'),
        ),
        migrations.AddIndex(
            model_name='activitecertification',
            index=models.Index(fields=['type_activite'], name='formations__type_ac_6e99ae_idx'),
        ),
        migrations.AddIndex(
            model_name='activitecertification',
            index=models.Index(fields=['date'], name='formations__date_d5b484_idx'),
        ),
        migrations.AddIndex(
            model_name='activitecertification',
            index=models.Index(fields=['cooperative', 'date'], name='formations__coopera_905dd1_idx'),
        ),
    ]
