# Generated by Django 5.2.7 on 2025-10-16 08:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0002_alter_cooperative_options_remove_cooperative_actif_and_more'),
        ('parcelles', '0001_initial'),
        ('producteurs', '0005_alter_producteur_date_naissance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotVanille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qr_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_recolte', models.DateField()),
                ('poids_vert_kg', models.DecimalField(decimal_places=2, help_text='Poids en kg (vanille verte)', max_digits=10)),
                ('poids_prepare_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Poids après préparation', max_digits=10, null=True)),
                ('nombre_gousses', models.IntegerField(blank=True, null=True)),
                ('qualite', models.CharField(choices=[('gourmet', 'Gourmet'), ('premium', 'Premium'), ('standard', 'Standard'), ('extraction', 'Extraction')], max_length=20)),
                ('taux_humidite', models.DecimalField(blank=True, decimal_places=2, help_text="Taux d'humidité en %", max_digits=5, null=True)),
                ('longueur_moyenne_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('recolte', 'Récolté'), ('preparation', 'En préparation'), ('stockage', 'En stockage'), ('expedition', 'Expédié'), ('reception', 'Reçu'), ('vendu', 'Vendu')], default='recolte', max_length=20)),
                ('hash_bloc', models.CharField(blank=True, editable=False, max_length=64)),
                ('hash_precedent', models.CharField(blank=True, default='', max_length=64)),
                ('photo_recolte', models.ImageField(blank=True, null=True, upload_to='tracabilite/recolte/')),
                ('certificat', models.FileField(blank=True, null=True, upload_to='tracabilite/certificats/')),
                ('notes', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_vanille', to='cooperatives.cooperative')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_modifies', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_vanille', to='parcelles.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_vanille', to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Lot de vanille',
                'verbose_name_plural': 'Lots de vanille',
                'ordering': ['-date_recolte', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='EvenementTracabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('recolte', '🌱 Récolte'), ('echaudage', '🔥 Échaudage'), ('etuvage', '🌡️ Étuvage'), ('sechage', '☀️ Séchage'), ('affinage', '⏳ Affinage'), ('tri', '📊 Tri/Classification'), ('conditionnement', '📦 Conditionnement'), ('controle_qualite', '✓ Contrôle qualité'), ('stockage', '🏭 Stockage'), ('expedition', '🚚 Expédition'), ('reception', '📥 Réception'), ('transformation', '⚙️ Transformation'), ('vente', '💰 Vente'), ('livraison', '🎁 Livraison client')], max_length=30)),
                ('date_evenement', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, help_text="Nom de l'entreprise/coopérative", max_length=200)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidite_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duree_heures', models.IntegerField(blank=True, null=True)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tracabilite/evenements/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('hash_evenement', models.CharField(blank=True, editable=False, max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='tracabilite.lotvanille')),
            ],
            options={
                'verbose_name': 'Événement de traçabilité',
                'verbose_name_plural': 'Événements de traçabilité',
                'ordering': ['date_evenement'],
            },
        ),
        migrations.CreateModel(
            name='TransfertLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de_organisation', models.CharField(max_length=200)),
                ('vers_organisation', models.CharField(max_length=200)),
                ('date_transfert', models.DateTimeField(default=django.utils.timezone.now)),
                ('poids_transfere_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bon_livraison', models.FileField(blank=True, null=True, upload_to='tracabilite/bons_livraison/')),
                ('facture', models.FileField(blank=True, null=True, upload_to='tracabilite/factures/')),
                ('accepte', models.BooleanField(default=False)),
                ('date_acceptation', models.DateTimeField(blank=True, null=True)),
                ('hash_transfert', models.CharField(blank=True, editable=False, max_length=64)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('de_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_emis', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='tracabilite.lotvanille')),
                ('vers_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_recus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfert de lot',
                'verbose_name_plural': 'Transferts de lots',
                'ordering': ['-date_transfert'],
            },
        ),
    ]
