# Generated by Django 5.2.7 on 2025-11-08 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracabilite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='certificat',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='photo_recolte',
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='bon_livraison',
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='facture',
        ),
        migrations.AddField(
            model_name='lotvanille',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='enfants', to='tracabilite.lotvanille'),
        ),
        migrations.AddField(
            model_name='transfertlot',
            name='client_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracabilite.clientfinal'),
        ),
        migrations.CreateModel(
            name='DocumentTracabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('FICHE_COLLECTE', 'Fiche de Collecte'), ('BON_ENTREE', "Bon d'Entrée"), ('BON_SORTIE', 'Bon de Sortie'), ('BON_TRANSPORT', 'Bon de Transport / Fiche de Convoi'), ('FACTURE', 'Facture'), ('CERTIFICAT_QUALITE', 'Certificat de Qualité'), ('AUTRE', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='tracabilite/documents/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracabilite.lotvanille')),
            ],
        ),
    ]
