# Generated by Django 5.2.7 on 2025-11-08 13:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_alter_cooperative_code'),
        ('producteurs', '0010_remove_historicalproducteur_enfants_doit_scolarises_and_more'),
        ('tracabilite', '0002_clientfinal_remove_lotvanille_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotvanille',
            name='producteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_vanille', to='producteurs.producteur'),
        ),
        migrations.CreateModel(
            name='LotProducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_contribue_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('part_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_producteurs', to='tracabilite.lotvanille')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions_lots', to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Contribution Producteur au Lot',
                'verbose_name_plural': 'Contributions Producteurs aux Lots',
                'unique_together': {('lot', 'producteur')},
            },
        ),
        migrations.AddField(
            model_name='lotvanille',
            name='producteurs',
            field=models.ManyToManyField(blank=True, related_name='lots_vanille_multiples', through='tracabilite.LotProducteur', to='producteurs.producteur'),
        ),
        migrations.CreateModel(
            name='VenteLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(default=django.utils.timezone.now)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_final', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracabilite.clientfinal')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='tracabilite.lotvanille')),
            ],
        ),
        migrations.CreateModel(
            name='VenteCooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids_vendu_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('part_pourcent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_groupes', to='cooperatives.cooperative')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives_participantes', to='tracabilite.ventelot')),
            ],
            options={
                'verbose_name': 'Participation Coopérative à la Vente',
                'verbose_name_plural': 'Participations Coopératives aux Ventes',
                'unique_together': {('vente', 'cooperative')},
            },
        ),
    ]
