# Generated by Django 5.2.7 on 2025-11-17 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0003_alter_cooperative_code'),
        ('parcelles', '0006_parcelle_productions_par_culture'),
        ('producteurs', '0012_historicalproducteur_satellite_floraison_and_more'),
        ('tracabilite', '0003_alter_lotvanille_producteur_lotproducteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('annee_debut', models.IntegerField()),
                ('annee_fin', models.IntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('cloturee', 'Clôturée')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['-annee_debut'],
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_colis', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type_colis', models.CharField(choices=[('carton', 'Carton'), ('sac', 'Sac'), ('caisse_bois', 'Caisse en bois'), ('container', 'Container')], max_length=20)),
                ('poids_net', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('poids_brut', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('qualite', models.CharField(max_length=20)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('date_conditionnement', models.DateField()),
                ('qr_code', models.CharField(blank=True, max_length=200, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-date_conditionnement', 'numero_colis'],
            },
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='client_final',
        ),
        migrations.RemoveField(
            model_name='ventelot',
            name='client_final',
        ),
        migrations.RemoveField(
            model_name='documenttracabilite',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='documenttracabilite',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='evenementtracabilite',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='evenementtracabilite',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='evenementtracabilite',
            name='responsable',
        ),
        migrations.AlterUniqueTogether(
            name='lotproducteur',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lotproducteur',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='lotproducteur',
            name='producteur',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='producteurs',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='cree_par',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='modifie_par',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='parcelle',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='lotvanille',
            name='producteur',
        ),
        migrations.RemoveField(
            model_name='ventelot',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='de_responsable',
        ),
        migrations.RemoveField(
            model_name='transfertlot',
            name='vers_responsable',
        ),
        migrations.AlterUniqueTogether(
            name='ventecooperative',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ventecooperative',
            name='cooperative',
        ),
        migrations.RemoveField(
            model_name='ventecooperative',
            name='vente',
        ),
        migrations.CreateModel(
            name='BonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bt', models.CharField(db_index=True, max_length=20, unique=True)),
                ('lieu_depart', models.CharField(max_length=200)),
                ('fokontany_depart', models.CharField(max_length=100)),
                ('lieu_destination', models.CharField(max_length=200)),
                ('type_logistique', models.CharField(choices=[('dos_homme', "Dos d'homme"), ('moto', 'Moto'), ('vehicule', 'Véhicule')], max_length=20)),
                ('numero_vehicule', models.CharField(blank=True, max_length=50)),
                ('type_vehicule', models.CharField(blank=True, max_length=50)),
                ('nom_chauffeur', models.CharField(blank=True, max_length=100)),
                ('telephone_chauffeur', models.CharField(blank=True, max_length=20)),
                ('date_chargement', models.DateField()),
                ('date_arrivee', models.DateField(blank=True, null=True)),
                ('poids_total_depart', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('poids_total_arrivee', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('agent_convoyeur', models.CharField(max_length=100)),
                ('agent_receptionnaire', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_transit', 'En transit'), ('recu', 'Reçu'), ('anomalie', 'Anomalie')], default='en_transit', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracabilite.campagne')),
            ],
            options={
                'verbose_name': 'Bon de transport (BT)',
                'verbose_name_plural': 'Bons de transport (BT)',
                'ordering': ['-date_chargement', '-numero_bt'],
            },
        ),
        migrations.CreateModel(
            name='BonCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fabc', models.CharField(db_index=True, max_length=20, unique=True)),
                ('est_vente_groupee', models.BooleanField(default=False)),
                ('date_marche', models.DateField()),
                ('village_marche', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('fokontany', models.CharField(max_length=100)),
                ('type_produit', models.CharField(choices=[('vanille_verte', 'Vanille Verte'), ('vanille_vrac', 'Vanille Vrac'), ('cafe', 'Café'), ('girofle', 'Girofle')], max_length=20)),
                ('certification', models.CharField(choices=[('g4g', 'G4G (Good 4 Good)'), ('bio', 'BIO'), ('ra', 'RA (Rainforest Alliance)'), ('ffl', 'FFL (Fair for Life)'), ('rauet', 'RAUEBT')], max_length=20)),
                ('poids_total_livre', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids total à la livraison (kg)')),
                ('poids_accepte', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids accepté/acheté (kg)')),
                ('poids_retour', models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Poids retour (kg)')),
                ('prix_unitaire_marche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire du marché (Ar/kg)')),
                ('montant_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant premium (Ar)')),
                ('montant_total_achat', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total achat (Ar)')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('mobile', 'Mobile Banking')], max_length=20)),
                ('montant_avances_anterieures', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant des avances antérieures (Ar)')),
                ('remboursement_par_vanille', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remboursement par vanille livrée (Ar)')),
                ('remboursement_especes', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remboursement en espèces (Ar)')),
                ('solde_avances', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde des avances (Ar)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producteurs.producteur')),
                ('producteurs_groupes', models.ManyToManyField(blank=True, help_text="Liste des producteurs dans le cas d'une vente groupée", related_name='bons_collecte_groupes', to='producteurs.producteur')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracabilite.campagne')),
            ],
            options={
                'verbose_name': 'Bon de collecte (FABC)',
                'verbose_name_plural': 'Bons de collecte (FABC)',
                'ordering': ['-date_marche', '-numero_fabc'],
            },
        ),
        migrations.CreateModel(
            name='CommandeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nom_client', models.CharField(max_length=200)),
                ('pays_destination', models.CharField(max_length=100)),
                ('ville_destination', models.CharField(max_length=100)),
                ('type_transport', models.CharField(choices=[('aerien', 'Aérien'), ('maritime', 'Maritime'), ('terrestre', 'Terrestre')], max_length=20)),
                ('numero_conteneur', models.CharField(blank=True, max_length=50)),
                ('numero_vol', models.CharField(blank=True, max_length=50)),
                ('date_commande', models.DateField()),
                ('date_expedition', models.DateField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_effective', models.DateField(blank=True, null=True)),
                ('poids_total_net', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('poids_total_brut', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('valeur_commande', models.DecimalField(decimal_places=2, help_text='Valeur en USD', max_digits=15)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CIF', 'CIF'), ('DDP', 'DDP')], default='FOB', max_length=10)),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('expedie', 'Expédié'), ('en_transit', 'En transit'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_preparation', max_length=20)),
                ('numero_facture', models.CharField(blank=True, max_length=50)),
                ('numero_bl', models.CharField(blank=True, max_length=50)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracabilite.campagne')),
                ('colis', models.ManyToManyField(related_name='commandes_export', to='tracabilite.colis')),
            ],
            options={
                'verbose_name': "Commande d'export",
                'verbose_name_plural': "Commandes d'export",
                'ordering': ['-date_commande', '-numero_commande'],
            },
        ),
        migrations.CreateModel(
            name='DetailSacBonCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sac', models.IntegerField()),
                ('poids_brut', models.DecimalField(decimal_places=3, max_digits=8)),
                ('tare', models.DecimalField(decimal_places=3, max_digits=8)),
                ('poids_net', models.DecimalField(decimal_places=3, max_digits=8)),
                ('bon_collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_sacs', to='tracabilite.boncollecte')),
            ],
            options={
                'ordering': ['numero_sac'],
                'unique_together': {('bon_collecte', 'numero_sac')},
            },
        ),
        migrations.CreateModel(
            name='DetailSacBonTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sac', models.IntegerField()),
                ('poids_sac_depart', models.DecimalField(decimal_places=3, max_digits=8)),
                ('poids_sac_arrivee', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('controle_reception', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], max_length=10)),
                ('remarques', models.TextField(blank=True, help_text='Ex: sac déchiré, perdu, écart de poids...')),
                ('bon_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details_sacs', to='tracabilite.bontransport')),
            ],
            options={
                'ordering': ['numero_sac'],
                'unique_together': {('bon_transport', 'numero_sac')},
            },
        ),
        migrations.CreateModel(
            name='FicheCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fc', models.CharField(db_index=True, max_length=20, unique=True)),
                ('certification', models.CharField(max_length=20)),
                ('date_marche', models.DateField()),
                ('fokontany', models.CharField(max_length=100)),
                ('nombre_producteurs', models.IntegerField(default=0)),
                ('poids_total_net', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('agent_re', models.CharField(max_length=100, verbose_name="Nom de l'agent RE")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bons_collecte', models.ManyToManyField(related_name='fiches_collecte', to='tracabilite.boncollecte')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracabilite.campagne')),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Fiche de collecte (FC)',
                'verbose_name_plural': 'Fiches de collecte (FC)',
                'ordering': ['-date_marche', '-numero_fc'],
            },
        ),
        migrations.AddField(
            model_name='bontransport',
            name='fiche_collecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_transport', to='tracabilite.fichecollecte'),
        ),
        migrations.CreateModel(
            name='LotTraitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(db_index=True, max_length=50, unique=True)),
                ('type_traitement', models.CharField(choices=[('sechage', 'Séchage'), ('fermentation', 'Fermentation'), ('triage', 'Triage'), ('conditionnement', 'Conditionnement')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('poids_entree', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('poids_sortie', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('perte_poids', models.DecimalField(decimal_places=3, default=0, help_text='Perte de poids durant le traitement (kg)', max_digits=8)),
                ('taux_perte', models.DecimalField(decimal_places=2, default=0, help_text='Taux de perte en %', max_digits=5)),
                ('qualite', models.CharField(blank=True, choices=[('gourmet', 'Gourmet'), ('tk1', 'TK1'), ('tk2', 'TK2'), ('cuts', 'Cuts')], max_length=20)),
                ('responsable_traitement', models.CharField(max_length=100)),
                ('site_traitement', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('valide', 'Validé')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bons_transport', models.ManyToManyField(related_name='lots_traitement', to='tracabilite.bontransport')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracabilite.campagne')),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cooperatives.cooperative')),
            ],
            options={
                'verbose_name': 'Lot de traitement',
                'verbose_name_plural': 'Lots de traitement',
                'ordering': ['-date_debut', '-numero_lot'],
            },
        ),
        migrations.AddField(
            model_name='colis',
            name='lot_traitement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis', to='tracabilite.lottraitement'),
        ),
        migrations.CreateModel(
            name='TracabiliteChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, editable=False, unique=True)),
                ('type_tracabilite', models.CharField(choices=[('ascendante', 'Ascendante (producteur → export)'), ('descendante', 'Descendante (export → producteur)')], max_length=20)),
                ('bon_collecte_id', models.IntegerField(blank=True, null=True)),
                ('fiche_collecte_id', models.IntegerField(blank=True, null=True)),
                ('bon_transport_id', models.IntegerField(blank=True, null=True)),
                ('lot_traitement_id', models.IntegerField(blank=True, null=True)),
                ('colis_id', models.IntegerField(blank=True, null=True)),
                ('commande_export_id', models.IntegerField(blank=True, null=True)),
                ('chain_data', models.JSONField(default=dict, help_text='Données complètes de la chaîne en JSON')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parcelles.parcelle')),
                ('producteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producteurs.producteur')),
            ],
            options={
                'verbose_name': 'Chaîne de traçabilité',
                'verbose_name_plural': 'Chaînes de traçabilité',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.DeleteModel(
            name='ClientFinal',
        ),
        migrations.DeleteModel(
            name='DocumentTracabilite',
        ),
        migrations.DeleteModel(
            name='EvenementTracabilite',
        ),
        migrations.DeleteModel(
            name='LotProducteur',
        ),
        migrations.DeleteModel(
            name='LotVanille',
        ),
        migrations.DeleteModel(
            name='TransfertLot',
        ),
        migrations.DeleteModel(
            name='VenteCooperative',
        ),
        migrations.DeleteModel(
            name='VenteLot',
        ),
    ]
