# Generated by Django 5.2.7 on 2025-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracabilite', '0004_campagne_colis_remove_transfertlot_client_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncollecte',
            name='certification',
            field=models.CharField(choices=[('g4g', 'G4G (Good 4 Good)'), ('bio', 'BIO'), ('ra', 'RA (Rainforest Alliance)'), ('ffl', 'FFL (Fair for Life)'), ('rauebt', 'RAUEBT')], max_length=20),
        ),
    ]
