# Generated by Django 5.2.7 on 2026-08-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_region'),
        ('producteurs', '0019_performance_indexes'),
        ('tracabilite', '0005_alter_boncollecte_certification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['campagne'], name='tracabilite_campagn_6f1b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['producteur'], name='tracabilite_product_471876_idx'),
        ),
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['cooperative'], name='tracabilite_coopera_78b117_idx'),
        ),
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['date_marche'], name='tracabilite_date_ma_41ae5a_idx'),
        ),
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['type_produit'], name='tracabilite_type_pr_86cb7c_idx'),
        ),
        migrations.AddIndex(
            model_name='boncollecte',
            index=models.Index(fields=['certification'], name='tracabilite_certifi_cf0fe4_idx'),
        ),
    ]
