# Generated by Django 5.2.7 on 2026-08-24 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_activitecertification_certification_cooperative_and_more'),
        ('tracabilite', '0006_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncollecte',
            name='type_certification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_collecte', to='formations.typecertification', verbose_name='Type de certification'),
        ),
        migrations.AlterField(
            model_name='boncollecte',
            name='certification',
            field=models.CharField(blank=True, choices=[('g4g', 'G4G (Good 4 Good)'), ('bio', 'BIO'), ('ra', 'RA (Rainforest Alliance)'), ('ffl', 'FFL (Fair for Life)'), ('rauebt', 'RAUEBT')], max_length=20, null=True),
        ),
    ]
