# Generated by Django 5.2.7 on 2026-08-27 05:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteurs', '0020_historicalproducteur_commune_ref_and_more'),
        ('tracabilite', '0008_migrate_certification_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom du magasin')),
                ('code', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Code')),
                ('type', models.CharField(choices=[('entrepot', 'Entrepôt'), ('depot_transit', 'Dépôt de transit'), ('site_exportateur', 'Site exportateur'), ('cooperative', 'Coopérative')], default='entrepot', max_length=30, verbose_name='Type de magasin')),
                ('localisation', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='campagne',
            name='type',
            field=models.CharField(choices=[('vanille_verte', 'Vanille verte'), ('vanille_preparee', 'Vanille préparée')], default='vanille_verte', max_length=20, verbose_name='Type de campagne'),
        ),
        migrations.CreateModel(
            name='BonLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro du bon')),
                ('produit', models.CharField(choices=[('vanille_verte', 'Vanille verte'), ('vanille_preparee', 'Vanille préparée'), ('vanille_vrac', 'Vanille vrac')], default='vanille_preparee', max_length=20, verbose_name='Produit')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité (kg)')),
                ('date', models.DateField(verbose_name='Date de livraison')),
                ('transporteur', models.CharField(blank=True, max_length=100, verbose_name='Transporteur')),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('preparee', 'Préparée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='preparee', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commande_export', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison', to='tracabilite.commandeexport', verbose_name="Transaction (commande d'export)")),
                ('magasin_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_destinations', to='tracabilite.magasin', verbose_name='Magasin de destination')),
                ('magasin_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_livraison_sorties', to='tracabilite.magasin', verbose_name='Magasin de départ')),
            ],
            options={
                'verbose_name': 'Bon de livraison',
                'verbose_name_plural': 'Bons de livraison',
                'ordering': ['-date', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='EntreeMagasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro du bon')),
                ('produit', models.CharField(default='vanille_preparee', max_length=20, verbose_name='Produit')),
                ('quantite_recue', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue (kg)')),
                ('date', models.DateField(verbose_name='Date de réception')),
                ('agent_receptionnaire', models.CharField(blank=True, max_length=100, verbose_name='Agent réceptionnaire')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bon_livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees', to='tracabilite.bonlivraison', verbose_name='Bon de livraison associé')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrees_magasin', to='tracabilite.magasin', verbose_name='Magasin de réception')),
            ],
            options={
                'verbose_name': 'Entrée magasin',
                'verbose_name_plural': 'Entrées magasin',
                'ordering': ['-date', '-numero_bon'],
            },
        ),
        migrations.CreateModel(
            name='EstimationProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_estimee', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité estimée (kg)')),
                ('type_vanille', models.CharField(choices=[('verte', 'Vanille verte'), ('preparee', 'Vanille préparée')], default='verte', max_length=20, verbose_name='Type de vanille')),
                ('date_estimation', models.DateField(verbose_name="Date de l'estimation")),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimations_production', to='tracabilite.campagne', verbose_name='Campagne')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations_production', to='producteurs.producteur', verbose_name='Producteur')),
            ],
            options={
                'verbose_name': 'Estimation de production',
                'verbose_name_plural': 'Estimations de production',
                'ordering': ['-date_estimation'],
                'unique_together': {('producteur', 'campagne', 'type_vanille')},
            },
        ),
        migrations.CreateModel(
            name='FicheStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='vanille_preparee', max_length=20, verbose_name='Produit')),
                ('date', models.DateField(verbose_name='Date du mouvement')),
                ('reference', models.CharField(blank=True, help_text='Référence document (BL, entrée, ajustement...)', max_length=100, verbose_name='Référence')),
                ('quantite_entree', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité entrée (kg)')),
                ('quantite_sortie', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité sortie (kg)')),
                ('solde', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=14, verbose_name='Solde cumulé (kg)')),
                ('type_mouvement', models.CharField(choices=[('entree_bl', 'Entrée sur bon de livraison'), ('entree_directe', 'Entrée directe'), ('sortie_export', 'Sortie pour export'), ('ajustement', 'Ajustement')], default='entree_directe', max_length=20, verbose_name='Type de mouvement')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_stock', to='tracabilite.magasin', verbose_name='Magasin')),
            ],
            options={
                'verbose_name': 'Fiche de stock',
                'verbose_name_plural': 'Fiches de stock',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['magasin', 'produit', '-date'], name='tracabilite_magasin_976483_idx')],
            },
        ),
    ]
