# Generated by Django 5.2.7 on 2026-09-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracabilite', '0009_magasin_campagne_type_bonlivraison_entreemagasin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncollecte',
            name='montant_total_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant total achat (Ar)'),
        ),
    ]
