# Generated by Django 5.2.7 on 2026-08-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0005_alter_cooperative_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du district')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la région')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la commune')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='geographie.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
                'unique_together': {('district', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'agence")),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agences', to='geographie.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Agence RAMEX',
                'verbose_name_plural': 'Agences RAMEX',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fokontany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du fokontany')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fokontanys', to='geographie.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Fokontany',
                'verbose_name_plural': 'Fokontany',
                'ordering': ['nom'],
                'unique_together': {('commune', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='geographie.region', verbose_name='Région'),
        ),
        migrations.CreateModel(
            name='StructureIntermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du représentant')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures_intermediaires', to='cooperatives.cooperative', verbose_name='Coopérative')),
                ('fokontany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='structures_intermediaires', to='geographie.fokontany', verbose_name='Fokontany')),
            ],
            options={
                'verbose_name': 'Structure intermédiaire',
                'verbose_name_plural': 'Structures intermédiaires',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'nom')},
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du village')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Code')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fokontany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villages', to='geographie.fokontany', verbose_name='Fokontany')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['nom'],
                'unique_together': {('fokontany', 'nom')},
            },
        ),
    ]
