# Generated by Django 5.2.7 on 2026-08-12 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cooperatives', '0007_cooperative_objectifs_dd'),
        ('producteurs', '0020_historicalproducteur_commune_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartenaireDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du partenaire')),
                ('type', models.CharField(choices=[('autorite_locale', 'Autorité locale'), ('ong', 'ONG'), ('partenaire_technique', 'Partenaire technique')], max_length=30, verbose_name='Type de partenaire')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Personne de contact')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partenaires_dd_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Partenaire Développement Durable',
                'verbose_name_plural': 'Partenaires Développement Durable',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteDD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('reboisement', 'Reboisement'), ('convention_partenariat', 'Convention de partenariat'), ('pepiniere', 'Production de jeunes plants / pépinière'), ('sensibilisation', 'Séance de sensibilisation'), ('formation', 'Formation'), ('audit_interne', 'Audit interne'), ('audit_externe', 'Audit externe')], max_length=30, verbose_name="Type d'activité")),
                ('date', models.DateField(verbose_name="Date de l'activité")),
                ('objectif_client', models.CharField(choices=[('resilience', 'Résilience des producteurs'), ('autonomisation_femmes', 'Autonomisation des femmes'), ('droits_humains', 'Droits humains (lutte contre le travail des enfants)'), ('biodiversite', 'Préservation de la biodiversité'), ('environnement', "Protection de l'environnement"), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Objectif client')),
                ('description', models.TextField(verbose_name="Description de l'activité")),
                ('resultat', models.TextField(blank=True, verbose_name='Résultat obtenu')),
                ('nombre_participants', models.PositiveIntegerField(default=0, verbose_name='Nombre de participants')),
                ('notes', models.TextField(blank=True, verbose_name='Notes complémentaires')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_dd', to='cooperatives.cooperative', verbose_name='Coopérative concernée')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_dd_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('producteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_dd', to='producteurs.producteur', verbose_name='Producteur concerné')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_dd_responsables', to=settings.AUTH_USER_MODEL, verbose_name='Agent RAMEX responsable')),
                ('partenaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites_dd', to='developpement_durable.partenairedd', verbose_name='Partenaire impliqué')),
            ],
            options={
                'verbose_name': 'Activité Développement Durable',
                'verbose_name_plural': 'Activités Développement Durable',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='partenairedd',
            index=models.Index(fields=['type'], name='developpeme_type_75eb0c_idx'),
        ),
        migrations.AddIndex(
            model_name='partenairedd',
            index=models.Index(fields=['actif'], name='developpeme_actif_ddee86_idx'),
        ),
        migrations.AddIndex(
            model_name='activitedd',
            index=models.Index(fields=['type_activite'], name='developpeme_type_ac_8f4f17_idx'),
        ),
        migrations.AddIndex(
            model_name='activitedd',
            index=models.Index(fields=['date'], name='developpeme_date_ca1f96_idx'),
        ),
        migrations.AddIndex(
            model_name='activitedd',
            index=models.Index(fields=['cooperative'], name='developpeme_coopera_d77c4c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitedd',
            index=models.Index(fields=['objectif_client'], name='developpeme_objecti_23018f_idx'),
        ),
    ]
