# Generated by Django 5.2.7 on 2026-01-14 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('view', 'Consultation'), ('export', 'Export'), ('import', 'Import'), ('other', 'Autre')], max_length=20, verbose_name='Action')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='Module')),
                ('description', models.TextField(verbose_name='Description')),
                ('object_type', models.CharField(blank=True, max_length=100, null=True, verbose_name="Type d'objet")),
                ('object_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Données supplémentaires')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_activ_timesta_622925_idx'), models.Index(fields=['user', '-timestamp'], name='users_activ_user_id_8a5363_idx'), models.Index(fields=['action', '-timestamp'], name='users_activ_action_04c071_idx')],
            },
        ),
    ]
