# Generated by Django 5.2.7 on 2026-08-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographie', '0001_initial'),
        ('users', '0002_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='geographie.agence', verbose_name='Agence RAMEX assignée'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('animateur', 'Animateur terrain'), ('superviseur', 'Superviseur'), ('agent_collecte', 'Agent de collecte')], default='animateur', max_length=20, verbose_name='Rôle'),
        ),
    ]
